# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  
  # fake_execution: true

  controller_names:
    - arm_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6



# controller_manager_ns: controller_manager
# controller_list:
#   - name: arm_group_controller
#     type: follow_joint_trajectory/FollowJointTrajectory  # 注意类型格式
#     joints: [J1, J2, J3, J4, J5, J6]
#     default: true  # 设为默认控制器
#     fake_execution: true